### PR TITLE
Compatibility updates

### PR DESCRIPTION
**Pull request by zikani03**
Includes updates for compatibility with php 5.4, support for non-conventional primary keys and a utility trait for getting audit sources

### CODE REVIEW

**Comment by rochamarcelo** [comment]
Thanks for all fixes.

**Comment by rochamarcelo** [comment]
Hi, I saw that "jippi/cakephp-audit-log" have merged my older pull request. Could you send a pull request to "jippi/cakephp-audit-log"? I have tried but its saying "Can't automatically merge".

Thanks again.

**Comment by zikani03** [comment]
I have sent a pull request and waiting to hear what they say. Thanks again!

**Comment by rochamarcelo** [comment]
Great.

**Pull request merged**
